### PR TITLE
Updating sprites

### PR DESCRIPTION
**Pull request by illbzo1**
This branch updates the sprites used to be My Little Pony sprites.

### CODE REVIEW

**Comment by jqr** [comment]
Screen Shot 2013-04-02 at 11 48 41 PM

**Comment by jqr** [comment]
While I don't condone pony-on-pony violence, I think this needs sounds to really tie it together.

**Comment by jqr** [comment]
This is improving.

**Comment by illbzo1** [comment]
I've downloaded some clips from a MLP soundboard and I want to use Audacity to cut them into more appropriate sound effects. 

I also want to make 5 enemy types based on each of the other 5 main ponies, each of which moves in a different pattern and has a different attack.

I took a look at the code you've pushed out for spawning more enemies and I've messed with movement pattern logic a bit, so it's just a matter of learning how to describe the way I want each pony to move.

**Comment by indymichelle** [comment]
NO MERGE FOR YOU!! :-1:

**Pull request closed without merging**
